version: '3'
services:
  web:
    build: .
    ports: 
      - "5000:5000"
    volumes:
      - ./data:/srv/WindNinjaServer/data

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "80:80"
