repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: bash -c 'cd WindNinja-Server/windninja_server && pipenv run isort'
        types: [python]
        files: WindNinja-Server/windninja_server

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: bash -c 'cd WindNinja-Server/windninja_server && pipenv run black .'
        types: [python]
        files: WindNinja-Server/windninja_server

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: bash -c 'cd WindNinja-Server/windninja_server && pipenv run flake8'
        types: [python]
        exclude: setup.py
        files: WindNinja-Server/windninja_server

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: bash -c 'cd WindNinja-Server/windninja_server && pipenv run pytest'
        types: [python]
        files: WindNinja-Server/windninja_server
