--- 
job_wrapper: 
  auto_forecasts:
    NOMADS-HIRES-ARW-ALASKA-5-KM: AQMAAAABAAAAFAAAAFKZYg7iPmDAqFePPXPFSUBqs6xZ6R5gwFA01GpAGkxAyn7Td5v3YMDYDL49Q31OQFZZ5YbCRWHAWO9x8tdgTkAs5ueGJoJhwJio8Grw7k5AjO26WUGJYcAwXa9T5vZRQJvNAYdyGmTAMF2vU+b2UUAzyetofOhkwHiG5I9iTFFAOMUalsUdZcAw1Qe9t1NQQLRGefBXiGXA0JwHet+1T0DTwRiWYeFkwAiBz1txNk1AaJlt8GNaZMBQb2wBF1NMQExCY9JhVmbAwAyzW8FhSkCejHDhwCtmwHCeEMVaN0lAsYcKlgl3Y8CwEi3FCgxMQE8g9oZ+7GLA0FEgtqs2TEB8L+F382FiwIDZsz2zi01AJCVR8LOFYcAIgc9bcTZNQLzBDbTfxWDAwAyzW8FhSkBSmWIO4j5gwKhXjz1zxUlA
    NOMADS-HRRR-CONUS-3-KM: AQYAAAACAAAAAQMAAAABAAAABAAAAOhYt9eoN1/AgKERUEegQkDAJKkNDT5fwDCkdGqgqkJA0KbWOvI2X8CwhigfNY5CQOhYt9eoN1/AgKERUEegQkABAwAAAAEAAAAbAAAArC8IaJ+oX8AYMG4u9AxIQAzTyCuTYV/ASKR/TCLGRkDoWLfXqDdfwIChEVBHoEJAIJK2K3N+XcDQX7DU4Ks/QFQDC5V8YlvAYHeCtgIePkAcD/SFjZtawGB3grYCHj5A5FV1DXUNWsBAXHK24jo8QDgB2HbWW1nAAKPzPcqsO0BodemUBBVYwOCOSbaidDhArJ4e0YBqV8BAlwpNuXM8QOTU2qOzFVXAQFxytuI6PEBoKgLR0JVUwCDSlwEOkThAkGY4DU3rU8CgmjKns603QLAYn3Z2slPA4Di346+PPkAsO9CyKo9SwLCGKB81jkJADAHCstIkUcDABi4Q9ptEQPBLnpSEiFDAKCr0xKpiRkBwaerf76RQwDg0yYi+/kdAXK/h0FhIUcAYMG4u9AxIQNSUUjoSAVLAaONyPcPwRkCMprWUbORSwOjFJvJX1EZAbO9pOvpcVMCYHOzEGnFFQAhMqXYGpFTAaONyPcPwRkDEHY9JQY5WwDhvYR+VN0hAvFvklDycV8DQQdGITvBIQID4thxsE1/A0EHRiE7wSECsLwhon6hfwBgwbi70DEhA
  dem_min_bounding_geom_wkb: AQYAAAACAAAAAQMAAAABAAAALAAAAAzP03/zcVTAsEVGP3iLOEAQkrZ/e21UwDBEGcGKjThAuGkl4OlrVMCwAUvfbo44QCA5QkCZVlTAINIJobqgOEAobkXATUZUwBCSOd9lrzhA4CpDgC9FVMCARMLgg7A4QPAuYiAKM1TA4Ghd32nOOEBsZLf/GS9UwNDOvIAF2DhAtNokoK4tVMCwd9iggNs4QDjZ6N85KlTAkCOy4GvkOECgx/ZfOCRUwCCG874c9DhADFMaoGscVMBwh9qA9gw5QHTBy79QGFTAAKYYIOEeOUA8RzjgrRdUwIBaRx/nITlA3LC/H1O9UMCY6DLge2dGQMSaXKAbvVDAcAiCAB9oRkAwUNy/M79QwHA5az+fc0ZA6Fbpn1byUMDom9/feIhHQGi1U8Ac/VDAkIR8oOKYR0AoihFg2QBRwMhh+p/HnUdA4LQCIJAKUcAIhDDgS6pHQIjZJyAmD1HAEN5g4LutR0CEDFGgdRJRwHh957+rrkdApIH/vz9LUcB4nN4fMbpHQPgu4h9wTlHA8CYOALW6R0D0ALD/SMpXwFBauP+1sUhAIA1AgMfKV8BIPpgAvrFIQEBnMCDhxV7AQFuGgCeASEDsTk4A2S1fwHD6mQCzMUhAdHhJYJMuX8A4zfo/zDBIQMDU8Z/tLl/AcDFIf9QUSEDcy1HA7SNfwLj1zx9Ca0VAHAW0n/IZX8AARPQ/qThEQJyzHKA0F1/AYBTwnwIiRECQMb4fExdfwJhXu2BpIURAXHQR4E3uXsBYyO2/WnVDQKTvEoDYHF7AGDuun2IEQUCsG7LfDuRdwDhw75+Mn0BAIAnSP5TiXcDQxGYftp1AQCiH598Tm13AeOrpv45mQECw9N3/Io1YwGBXZAC+DTpAHCC4nwxbWMDgiuzfE9Y5QDTvxz91gFTAkKODHvqGOEAMz9N/83FUwLBFRj94izhAAQMAAAABAAAAHQAAACiuB8DRVWDAcCO7YKdbS0D83ay/z1RgwEh2AsAUXEtAIJXq34lUYMDQo1YfNVxLQA6nIcDIS2DA4P5jQFRzS0BclQRgeklgwIDT9t+2ektAqIYTgFZIYMDoggmheH9LQFD28h+7P2DACDi1PpajS0BgEO//rD9gwDivy/9jpEtASlENoEJAYMBI+a+fGPVLQA4wBmBXQGDAWGIpAAAATEBAwQWgXkFgwODQ9l8xB0xAMKgHQMCfYcBITr3fQ2lRQJRm3p8U2GHAJF+5Hy6DUUBSjAngyedhwFhAe+AAilFAOXvq3+eOY8C8egqg/9hRQDvk8N9ej2PACHiYfwDZUUAt9vJ/5vFjwKi6C8BmtFFAmrwWIFY8ZMCc2bu/PpVRQL/Hy1+KQmTA7Lbi38mRUUCgnByAw0dkwJCkFiDCjlFAD0rn39jGZMAgjh4gcDhRQFFA+B9Ux2TAgKvMfxk4UUCUKvhf1NpkwPiakD/YFVFAevvS/+x3ZcBA3qTgZORPQPrd1Z/JYWbAMCKI/xXLSUABAAAghWRmwEAp5p/aoklA4j8kYFhkZsCwmqiAsJ1JQJ/lBmD6Y2bAEHyfgK2bSUAorgfA0VVgwHAju2CnW0tA
  in_dem_path: /srv/WindNinjaServer/data/dem/windninja_dem.vrt
  job_datastore: /srv/WindNinjaServer/data/job
  job_filename: job.json
  messages: 
    bbox_outside_dem: "Job domain is outside the supported DEM bounds"
    bbox_outside_forecasts: "Job domain is outside the supported auto forecast bounds"
  out_dem_filename: dem.tif
  queue_datastore: /srv/WindNinjaServer/data/queue
  tile_grabber: 
    file_template: "{0}.jpg"
    max_level: 12
    min_level: 1
    urls: 
      topofire: "https://topofire.dbs.umt.edu/topofire_v2/data/osmUShydro/{0}/{1}/{2}.png"
  tile_maker: 
    file_name: tiles
    zip_name: tiles.zip
    max_level: 14
    min_level: 1
    max_threads: 2
  wn_cli: 
    args_da: 
      - "--output_path $output_path"
      - "--elevation_file $elevation_file"
      - "--mesh_choice $mesh_choice"
      - "--num_threads $num_threads"
      - "--vegetation $vegetation"
      - "--time_zone $time_zone"
      - "--initialization_method $initialization_method"
      - "--input_speed $input_speed"
      - "--input_speed_unit $input_wind_height"
      - "--input_wind_height $input_wind_height"
      - "--units_input_wind_height $units_input_wind_height"
      - "--output_speed_units $output_speed_units"
      - "--output_wind_height $output_wind_height"
      - "--units_output_wind_height $units_output_wind_height"
      - "--write_shapefile_output $write_shapefile_output"
      - "--write_wx_model_shapefile_output $write_wx_model_shapefile_output"
      - "--write_goog_output false"
      - "--write_ascii_output $write_ascii_output"
      - "--momentum_flag $momentum_flag"
    args_wx: 
      - "--output_path $output_path"
      - "--elevation_file $elevation_file"
      - "--mesh_choice $mesh_choice"
      - "--num_threads $num_threads"
      - "--vegetation $vegetation"
      - "--time_zone $time_zone"
      - "--initialization_method $initialization_method"
      - "--wx_model_type $wx_model_type"
      - "--forecast_duration $forecast_duration"
      - "--output_speed_units $output_speed_units"
      - "--output_wind_height $output_wind_height"
      - "--units_output_wind_height $units_output_wind_height"
      - "--write_shapefile_output $write_shapefile_output"
      - "--write_wx_model_shapefile_output $write_wx_model_shapefile_output"
      - "--write_goog_output false"
      - "--write_ascii_output $write_ascii_output"
      - "--momentum_flag $momentum_flag"
    defaults: 
      forecast_duration: 3
      input_speed: 5
      input_speed_units: mph
      input_wind_height: 20
      mesh_choice: coarse
      num_threads: 4
      output_speed_units: mph
      output_wind_height: 20.0
      time_zone: auto-detect
      units_input_wind_height: ft
      units_output_wind_height: ft
      vegetation: grass
      momentum_flag: true
    env:
      FOAM_INST_DIR: /home/ubuntu/src/
    path: "foamDotFile=$$FOAM_INST_DIR/OpenFOAM-2.2.x/etc/bashrc && [ -f $$foamDotFile ] && . $$foamDotFile ; /usr/local/bin/WindNinja_cli"
mail: 
  from_address: wind.ninja.support@gmail.com
  support_address: wind.ninja.support@gmail.com
